### ISSUE TITLE
[Refactor] 예약 진행 페이지 로직 수정

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#73]
## 📔 Description

- 예약 진행 페이지 최종 로직 수정

## 🐈 Todo

- [ ] 예약 진행 페이지 최종 로직 수정

**Comment by seolbotdae** [comment]
프로젝트 계획 변경으로 작업 중단

**Comment by yh-project** [comment]
프로젝트 계획 변경으로 작업 중단
